//
//  CFDNSResolverTests.swift
//  Partout
//
//  Created by Davide De Rosa on 12/2/24.
//  Copyright (c) 2025 Davide De Rosa. All rights reserved.
//
//  https://github.com/passepartoutvpn
//
//  This file is part of Partout.
//
//  Partout is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Partout is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with Partout.  If not, see <http://www.gnu.org/licenses/>.
//

import _PartoutVendorsApple
import Foundation
import XCTest

final class CFDNSResolverTests: XCTestCase {
//    func test_givenResolver_whenResolveBeforeTimeout_thenReturnsResolvedRecords() async throws {
//        let hostname = "fixed.it"
//        let records = [DNSRecord(address: "5.9.152.28", isIPv6: false)]
//        let sut = SimpleDNSResolver {
//            CFDNSStrategy(hostname: $0)
//        }
//        let result = try await sut.resolve(hostname, timeout: 1000)
//        XCTAssertEqual(result, records)
//    }
//
//    func test_givenResolver_whenResolveAfterTimeout_thenFailsWithTimeout() async throws {
//        let hostname = "fixed.it"
//        let sut = SimpleDNSResolver {
//            CFDNSStrategy(hostname: $0)
//        }
//        do {
//            _ = try await sut.resolve(hostname, timeout: 1)
//            XCTFail(".resolve must fail")
//        } catch let error as PartoutError {
//            XCTAssertEqual(error.code, .dnsFailure)
//        } catch {
//            XCTFail("Unexpected error: \(error)")
//        }
//    }
}
